### ISSUE TITLE
Configuración de travis en servidor

### ISSUE THREAD

**Issue by pabloalbanese** [pabloalbanese/taller2#11]

**Comment by JicLotus** [comment]
Esta hecho, solo que hay que subir el .yml desde el administrador del repositorio.

**Comment by JicLotus** [comment]
Travis funcionando desde el viernes. Simplemente entrar en https://travis-ci.org/pabloalbanese/taller2 y ver cuales tests fallan y cuales no. A cada commit se actualizan los tests en travis. Igualmente manda mails diciendo si fallaron o no los tests a cada commit.
