### ISSUE TITLE
Formatos fecha en File.cpp

### ISSUE THREAD

**Issue by pabloalbanese** [pabloalbanese/taller2#20]
Se necesita resolver el envío y recepción de las propiedades tipo time_t de File.cpp y FileVersion ya que las propiedades de nombre lastModifiedOn (file) y date (fileVersion) no se están visualizando bien en el json.

Por ejemplo un json de file esta devolviendo esto:

"lastModifiedOn" : 1442683303

Y debería devolver algo mostrable por pantalla. Cuando se crea un file o un FileVersion ya se esta seteando la fecha y hora actual con setencias asi:

file->SetLastModifiedOn(time(0));

Si es necesario se pueden cambiar.

Tener en cuenta que estas dos propiedades solo son seteadas en el servidor y en el json solamente se tienen que devolver, es decir nunca se recibe de un json un valor que luego se setee en estas propiedades.

**Comment by kevinmlew** [comment]
Cuando haces un time(0) te devuelve algo de la forma 1443021439. Se esta guardando en formato timestamp, para mi es la mejor forma de guardarlo. Que el cliente lo reciba asi y si lo quiere mostrar por pantalla que antes haga algo como Utils.ConvertTimestampToDate()

**Comment by pabloalbanese** [comment]
OK cuando tengamos mas avanzado el tema del cliente y empecemos a mostrar la fecha lo retomamos al tema entonces.
