### ISSUE TITLE
Implementar funcionalidad Búsqueda de archivos

### ISSUE THREAD

**Issue by pabloalbanese** [pabloalbanese/taller2#26]
Implementa en el cliente la funcionalidad de buscar archivos dentro de los archivos accesibles por un usuario (los propios mas lo shared)

**Comment by eliventura** [comment]
Ya está la búsqueda por nombre, extensión y tags dentro de los archivos propios del usuario. Falta por owner y buscar dentro de los shared files (para la próxima entrega)
