### ISSUE TITLE
Crear capa de datos para rocksdb

### ISSUE THREAD

**Issue by pabloalbanese** [pabloalbanese/taller2#6]
Crear un archivo de nombre Data.cpp que contenga 4 métodos básicos estáticos que accedan a la BD de rocksdb. Estos métodos son el 

1. Insert(string key, string value)
2. Update(string key, string value)
3. string Get(string key)
4. Delete(string key)

Probarlos con el main que esta en Servidor.cpp

**Comment by eliventura** [comment]
Listo
